### ISSUE TITLE
Re-structure folder

### ISSUE THREAD

**Issue by jmaicaaan** [jmaicaaan/express-starter-ts#31]
As discussed, we will have some folder structures in our `src` folder to minimize the folders or the confusion for the developers as it currently mixing the app files and with the migrations and seeds.

Proposed folder structure
As discussed, we will have some folder structures in our `src` folder to minimize the folders or the confusion for the developers as it currently mixing the app files and with the migrations and seeds.

Proposed folder structure

  - src
    - app
      - controllers
      - common
        - enums
        - middlewares
        - repositories
        - services
        - utils
      - entities
      - tests
    - migrations
    - seeds
    - server.ts

@ciiidi, let me know your thoughts with my proposed folder structure & let's add this into `next` branch!

**Comment by ciiidi** [comment]
Ok @jmaicaaan I will post here the my proposed folder structure, somehow similar on yours.

**Comment by ciiidi** [comment]
![untitled diagram1](https://user-images.githubusercontent.com/19199918/35279059-e2cbf82e-0086-11e8-9b02-8c53b1b19217.png)
Proposed folder structure

- app
- database
- services
app contains the api logic, this is what we are building
database is just a separate module, it just happens that the application we are building needs a storage so we should separate its logic on our application.
services like a database, its like a module that needed by the application we are building

**Comment by ciiidi** [comment]
If the app needs to run the migrations, it should import the database for the app to run the migrations, because migration is part of the storage before it became a part of the app. Same way with the others

**Comment by ciiidi** [comment]
done in feature/next branch

**Comment by jmaicaaan** [comment]
Nice! I've initially looked on it and it looks good just got a few minors so far. Let me get back to you. Will prioritize this over the other tickets asap!

**Comment by jmaicaaan** [comment]
Hi @ciiidi ,

Good job so far on the re-restructuring our folders. The separation of app and database is I think a much better space right now than before. I don't have much comments on it, just a few hits only:

- Why make the `server.ts` IIFE? Also what's with the `async` doing there?

- I see what  you did with the integration testing, should we really do the opening and closing of database per test suite? I get the idea of we can isolate and single run the tests though

- Is the unit tests only for repositories? I think if the client wants to unit tests the services as unit. Would it be possible too?

- Is the `cli.js` will be part of this also? If yes, then let's make also everything working as master branch

**Comment by jmaicaaan** [comment]
Also note on this, bring back the `npm run setup:config` as we need it for Travis CI
