### ISSUE TITLE
Refactor configuration. Minimize the config files

### ISSUE THREAD

**Issue by cedrickmandocdoc** [jmaicaaan/express-starter-ts#37]

**Comment by ciiidi** [comment]
Note: 
-edit also the tsconfig use the default proper tsconfig generated by typescript.
-edit also the package.json remove if there are unnecessary run scripts
-see nodemon.json, can we remove that and run it package.json. because there are too many configs on root folder

**Comment by jmaicaaan** [comment]
Hmmm I was thinking with the nodemon.json config... If we would to convert the config into npm run scripts I think it would be unclear if someone unfamiliars look on it or would be adding a new config. What do you think? Or maybe that isnt a big deal

**Comment by ciiidi** [comment]
Ok also not big deal for me for nodemon.json Thanks

**Comment by jmaicaaan** [comment]
What do you mean with the ` tsconfig use the default proper tsconfig generated by typescript.`? Enlighten me more on that
