### ISSUE TITLE
Refactor test scripts.

### ISSUE THREAD

**Issue by cedrickmandocdoc** [jmaicaaan/express-starter-ts#38]
Add tests for:
-unit
-end 2 end
-integration

Sit the test next to implementation. There is WIP of this on the next branch

**Comment by jmaicaaan** [comment]
What is the test for integration vs e2e?

**Comment by ciiidi** [comment]
https://codeutopia.net/blog/2015/04/11/what-are-unit-testing-integration-testing-and-functional-testing/ I think this hold enough information for that, though are main focus for testing right now is e2e. But we are preparing the folder structure to adopt if we will gonna add a test for the 2 remaining

**Comment by jmaicaaan** [comment]
Got it, I see what you did in the `next` branch. Let's do it then, you can see my comments [here](https://github.com/jmaicaaan/express-starter-ts/issues/31)
